name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install

      - run: ./release.sh

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/heads/')
        with:
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: "jmapweb.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}-latest

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "jmapweb.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}

